# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Protein', '0002_auto_20171208_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 16, 9, 21, 59405)),
        ),
    ]
