# Generated by Django 2.0.2 on 2018-03-27 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Protein', '0003_profile_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comment',
            field=models.FileField(max_length=50000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 27, 16, 15, 10, 608345)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='testfile',
            field=models.FileField(max_length=50000, upload_to=''),
        ),
    ]
